### ISSUE TITLE
1. CRIE A TELA DE LOGIN, ONDE A PESSOA QUE JOGA DEVE PREENCHER AS INFORMAÇÕES PARA INICIAR UM JOGO

### ISSUE THREAD

**Issue by herculesgabriel** [herculesgabriel/trivia-react-redux#3]

**Comment by herculesgabriel** [comment]
## Criar a tela de login contendo as informações de nome e email, onde a pessoa que joga deve conseguir escrever seu nome e email nos inputs e o botão de jogar deve estar desabilitado caso não tenha alguma dessas informações.

- Recomendamos que o Redux e o Router sejam configurados nesse requisito, para que os demais possam ser feitos paralelamente!

### Observações técnicas

- [ ] A pessoa que joga deve conseguir escrever seu nome no input de texto
- [ ] A pessoa que joga deve conseguir escrever seu email no input de email
- [ ] O botão "Jogar" deve ser desabilitado caso email e/ou nome não estejam preenchidos
- [ ] O campo de texto para o nome deve possuir o atributo data-testid com o valor input-player-name
- [ ] O campo de texto para o email deve possuir o atributo data-testid com o valor input-gravatar-email
- [ ] O botão "Jogar" que leva a pessoa ao jogo deve possuir o atributo data-testid com o valor btn-play

### O que será avaliado

- [ ] Escreve o nome da pessoa jogadora
- [ ] Escreve o email da pessoa jogadora
- [ ] Botão Jogar desabilitado quando pessoa jogadora não preencher nenhum campo
- [ ] Botão Jogar desabilitado quando pessoa jogadora escrever apenas o nome
- [ ] Botão Jogar desabilitado quando pessoa jogadora escrever apenas o email
- [ ] Botão Jogar habilitado quando pessoa jogadora preencher os campos de nome e email

**Comment by mustang-roy** [comment]
Existem impedimentos para implementação usando o componente de Login? Algo que seja impossibilitado pelos testes?
